---

- hosts: all
  become: true
  tasks:
  
  - name: update repo
    apt: 
     update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install net-tools
    apt:
     name: net-tools
     state: latest
    when: ansible_distribution == "Ubuntu"


  - name: update repo
    yum:
     update_cache: yes
    when: ansible_distribution_version == "CentOS"

  - name: install net-tools
    yum:
     name: net-tools
     state: latest
    when: ansible_distribution == "CentOS"
